# Generated by Django 6.0.2 on 2026-03-04 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlists", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="watchlist",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="watchlistitem",
            options={"ordering": ["added_at"]},
        ),
        migrations.AddField(
            model_name="watchlistitem",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
